start: "2025-03-01T00:00"
end: "2025-03-01T06:00"
step: "PT1H"
grib_index_root: "indexes"
file_finder: "path/to/find_gribs.py"

rechunk_to:
  time: 1
  x: 200
  y: 200

data_collection:
  height_levels:
    - level_type: heightAboveGround
      variables:
        t: [50, 100]
        r: [50, 100]
        u: [50, 100]
        v: [50, 100]

  pressure_levels:
    - level_type: isobaricInhPa
      variables:
        z: [1000, 925, 850, 700, 500]
        t: [1000, 925, 850, 700, 500]

  single_levels:
    - level_type: heightAboveGround
      variables:
        hcc: null
        mld: null
    - level_type: heightAboveSea
      variables:
        pres: null
      level_name_mapping: "{var_name}_seasurface"
